version: '3'
services:
  web:
    image: php:7.3-apache
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 3000:80

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/:/var/lib/mysql:rw
      - ./config/my.conf:/etc/mysql/conf.d/config-file.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ABC12abc